version: "3"

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: eonx
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eonx_technical_task
    ports:
      - 5432
